## Comparison of Identified Substructures with Apogee

In [2]:
from Analysis import apogee_metallicities
lower_pm_results = 'data/matched_clusters_LowerPM.json'
higher_pm_results = 'data/matched_clusters_HigherPM.json'

## Function Overview: `apogee_metallicities`

This function performs a cross-match between Gaia stellar cluster data and APOGEE DR17 metallicity data, enhancing the cluster information with detailed metallicity measurements and incorporating external data from the Harris 2010 globular cluster catalog.

**Key Operations:**

1.  **Data Loading:**
    * Loads cluster data from a JSON file, which includes Gaia EDR3 source IDs for stars within each cluster.
    * Loads APOGEE DR17 allStarLite FITS file containing stellar metallicity information.
    * Loads metallicity data for Milky Way globular clusters from the Harris 2010 catalog.

2.  **Cross-Matching:**
    * Matches Gaia source IDs from the cluster data with corresponding entries in the APOGEE DR17 data.

3.  **Metallicity Calculation:**
    * Calculates statistical properties of metallicity for each cluster, including:
        * Mean and standard deviation of iron abundance ([Fe/H])
        * Mean and standard deviation of total metallicity ([M/H])
        * Mean and standard deviation of alpha-element enhancement ([Î±/M])

4.  **Integration of Harris 2010 Data:**
    * Merges metallicity values from the Harris 2010 catalog with the calculated cluster statistics, where available.

5.  **Filtering and Output:**
    * Filters the resulting data to include only clusters with a specified minimum number of matched stars and available Harris 2010 metallicity values.
    * Outputs two Pandas DataFrames:
        * A full summary of all clusters with APOGEE metallicities.
        * A filtered table meeting the specified criteria.

In [3]:
apogee_metallicities(lower_pm_results, apogee_fits_path = 'data/ApogeeDR17_allStarLite.fits', harris_data_path = 'data/harris2010_mwgc.dat', matched_star_threshold=10)

2025-03-18 22:25:31,627 - INFO - Total Gaia IDs that will be attempted to match with APOGEE: 951261
2025-03-18 22:25:34,110 - INFO - Successfully loaded 733901 stars from APOGEE DR17.
2025-03-18 22:25:34,390 - INFO - Matched 15018 Gaia stars with APOGEE metallicities: While trying to find 951261 Gaia IDS in 733901 APOGEE items.
2025-03-18 22:25:34,391 - INFO - Calculating statistics for each cluster with available apogee data.
2025-03-18 22:25:35,027 - INFO - Successfully merged Harris 2010 metallicities with cluster statistics for those stars available.

Full Cluster Statistics Table:

,Cluster Name,Matched Stars,Mean Fe_H,Std Dev Fe_H,Mean M_H,Std Dev M_H,Mean Alpha_M,Std Dev Alpha_M,Harris_Fe_H
0,NGC 6723,3,-0.996967,0.065984,-0.996900,0.072774,0.248112,0.037675,-1.10
1,"Terzan 7, Arp 2, Terzan 8",35,-0.708377,0.284330,-0.733980,0.291936,-0.006310,0.057999,NaN
2,Sagittarius,333,-0.651908,0.325162,-0.671014,0.342800,-0.013333,0.074107,NaN
3,NGC 6864,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.29
4,NGC 6426,0,NaN,NaN,NaN,NaN,NaN,NaN,-2.15
5,NGC 6981,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.42
6,NGC 5272,90,-1.415466,0.082010,-1.432552,0.092057,0.165441,0.067294,-1.50
7,NGC 7492,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.78
8,NGC 7089,5,-1.446840,0.046079,-1.459340,0.066376,0.167600,0.065497,-1.65
9,NGC 6205,30,-1.466709,0.120871,-1.441548,0.130366,0.161400,0.092266,-1.53
10,NGC 7078,84,-2.289832,0.095281,-2.213170,0.142825,0.198444,0.163315,-2.37
11,NGC 6229,8,-1.241987,0.073914,-1.254175,0.085568,0.181167,0.088982,-1.47
12,Draco,34,-1.804347,0.329438,-1.916018,0.336117,0.006997,0.154682,NaN
13,Ursa Minor,25,-1.909792,0.258089,-2.039224,0.242221,0.114100,0.145945,NaN
14,NGC 2419,0,NaN,NaN,NaN,NaN,NaN,NaN,-2.15
15,NGC 1904,36,-1.517931,0.133169,-1.514494,0.158816,0.122124,0.073902,-1.60
16,Fornax,106,-1.087188,0.323550,-1.134690,0.330720,-0.072057,0.088804,NaN
17,NGC 1851,38,-1.142199,0.195719,-1.160312,0.223550,0.193615,0.149167,-1.18
18,NGC 2298,7,-1.802400,0.061027,-1.779743,0.077416,0.161013,0.116218,-1.92
19,NGC 4147,3,-1.627967,0.078389,-1.631200,0.107999,0.229168,0.047879,-1.80
20,Carina,26,-1.688100,0.282346,-1.770635,0.317160,0.050035,0.178589,NaN
21,"LMC, Pictor II",11372,-0.714835,0.274414,-0.721143,0.293314,0.022442,0.073296,NaN
22,NGC 1261,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.27
23,NGC 2808,76,-1.072369,0.074776,-1.071958,0.089633,0.134176,0.076219,-1.14
24,Sculptor,58,-1.599322,0.408217,-1.655978,0.413898,0.059783,0.176154,NaN
25,SMC,2693,-1.036063,0.266374,-1.057925,0.285032,0.002105,0.084128,NaN
26,NGC 4590,28,-2.243825,0.084001,-2.181136,0.119711,0.244560,0.107611,-2.23
27,Rup 106,2,-1.306100,0.046386,-1.348500,0.048932,-0.047269,0.015578,-1.68
28,IC 4499,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.53
29,NGC 5286,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.69
30,NGC 6101,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.98
31,NGC 5694,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.98
32,NGC 5824,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.91
33,NGC 5024,22,-1.895618,0.083803,-1.886745,0.098775,0.227940,0.069794,-2.10
34,NGC 5053,13,-2.195192,0.120751,-2.163192,0.139464,0.230083,0.099679,-2.27
35,NGC 5634,2,-1.720100,0.080893,-1.712600,0.128976,0.195810,0.091125,-1.88

Filtered Clusters (Matched Stars > 10 and valid Harris_Fe_H):

,Cluster Name,Matched Stars,Mean Fe_H,Std Dev Fe_H,Mean M_H,Std Dev M_H,Mean Alpha_M,Std Dev Alpha_M,Harris_Fe_H
6,NGC 5272,90,-1.415466,0.082010,-1.432552,0.092057,0.165441,0.067294,-1.50
9,NGC 6205,30,-1.466709,0.120871,-1.441548,0.130366,0.161400,0.092266,-1.53
10,NGC 7078,84,-2.289832,0.095281,-2.213170,0.142825,0.198444,0.163315,-2.37
15,NGC 1904,36,-1.517931,0.133169,-1.514494,0.158816,0.122124,0.073902,-1.60
17,NGC 1851,38,-1.142199,0.195719,-1.160312,0.223550,0.193615,0.149167,-1.18
23,NGC 2808,76,-1.072369,0.074776,-1.071958,0.089633,0.134176,0.076219,-1.14
26,NGC 4590,28,-2.243825,0.084001,-2.181136,0.119711,0.244560,0.107611,-2.23
33,NGC 5024,22,-1.895618,0.083803,-1.886745,0.098775,0.227940,0.069794,-2.10
34,NGC 5053,13,-2.195192,0.120751,-2.163192,0.139464,0.230083,0.099679,-2.27

In [5]:
apogee_metallicities(higher_pm_results, apogee_fits_path = 'data/ApogeeDR17_allStarLite.fits', harris_data_path = 'data/harris2010_mwgc.dat', matched_star_threshold=20)

2025-03-18 22:26:14,735 - INFO - Total Gaia IDs that will be attempted to match with APOGEE: 231910
2025-03-18 22:26:15,618 - INFO - Successfully loaded 733901 stars from APOGEE DR17.
2025-03-18 22:26:15,731 - INFO - Matched 1231 Gaia stars with APOGEE metallicities: While trying to find 231910 Gaia IDS in 733901 APOGEE items.
2025-03-18 22:26:15,731 - INFO - Calculating statistics for each cluster with available apogee data.
2025-03-18 22:26:15,822 - INFO - Successfully merged Harris 2010 metallicities with cluster statistics for those stars available.

Full Cluster Statistics Table:

,Cluster Name,Matched Stars,Mean Fe_H,Std Dev Fe_H,Mean M_H,Std Dev M_H,Mean Alpha_M,Std Dev Alpha_M,Harris_Fe_H
0,NGC 5904,23,-1.198380,0.096100,-1.215857,0.108293,0.197006,0.076065,-1.29
1,NGC 7099,0,NaN,NaN,NaN,NaN,NaN,NaN,-2.27
2,NGC 6981,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.42
3,NGC 5272,25,-1.415905,0.079073,-1.426977,0.090835,0.162770,0.063794,-1.50
4,NGC 5466,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.98
5,NGC 6205,10,-1.517410,0.084477,-1.509200,0.143005,0.171105,0.090042,-1.53
6,NGC 7078,17,-2.259271,0.099400,-2.154324,0.104972,0.153626,0.123457,-2.37
7,NGC 6341,4,-2.189650,0.043032,-2.144100,0.067707,0.207694,0.110636,-2.31
8,NGC 1904,2,-1.489550,0.123673,-1.496150,0.148705,0.167799,0.082259,-1.60
9,NGC 1851,7,-1.139651,0.100045,-1.145114,0.115853,0.222932,0.106789,-1.18
10,NGC 1261,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.27
11,LMC,859,-0.699194,0.271344,-0.704635,0.288598,0.028399,0.063033,NaN
12,NGC 3201,15,-1.327800,0.067165,-1.358933,0.089247,0.172052,0.051012,-1.59
13,SMC,252,-0.980524,0.225059,-0.997138,0.238084,-0.003865,0.068967,NaN
14,NGC 4590,4,-2.267825,0.139087,-2.271600,0.124447,0.332980,0.051452,-2.23
15,NGC 362,3,-1.078833,0.041573,-1.086667,0.060598,0.142763,0.066107,-1.26
16,NGC 104,6,-0.728618,0.049435,-0.721407,0.050875,0.268412,0.020320,-0.72
17,NGC 5024,4,-1.897725,0.045078,-1.872025,0.077005,0.227297,0.071257,-2.10
18,NGC 6752,10,-1.504970,0.107211,-1.483140,0.123929,0.230285,0.067661,-1.54

Filtered Clusters (Matched Stars > 20 and valid Harris_Fe_H):

,Cluster Name,Matched Stars,Mean Fe_H,Std Dev Fe_H,Mean M_H,Std Dev M_H,Mean Alpha_M,Std Dev Alpha_M,Harris_Fe_H
0,NGC 5904,23,-1.198380,0.096100,-1.215857,0.108293,0.197006,0.076065,-1.29
3,NGC 5272,25,-1.415905,0.079073,-1.426977,0.090835,0.162770,0.063794,-1.50